name: ci

on:
  pull_request:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - run: pnpm run test
      - name: Compile sass
        run: pnpm run sass-prod
      - name: Test rollup build
        run: pnpm run prod
