name: ci

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Compile sass
        run: npm run sass-prod
      - name: Test rollup build
        run: npm run prod
